language: c

dist: xenial

compiler:
  - gcc

before_install:
  - echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y postgresql-12 postgis liblwgeom-dev libpq-dev libpqtypes-dev postgresql-server-dev-11 libproj-dev postgresql-11-postgis-2.5 postgresql-11-postgis-2.5-scripts libjson-c-dev
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -DWITH_COVERAGE=1 ..

script: 
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - make && make test

after_failure: ../test/scripts/print_fail.sh

after_success: coveralls --exclude src/debug --exclude point/src/debug --exclude include --exclude point/include --exclude src/sql --exclude point/src/sql --exclude doc --exclude test --exclude point/test --gcov-options '\-lp' -r .. -b .

